name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: ["main"]

jobs:
  buildAndRunContainer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage:$(date +%s)

    - name: Run the Docker container
      run: docker run -d -p 8080:80 myimage:$(date +%s)

