name: Docker Image CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  buildAndRunContainer:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag myimage

    - name: Login to the dockerhub
      run: docker login -u porwalmohit1999 -p Mohit@202

    - name: Push to image to the registry
      run: docker push myimage
      
    - name: Run the Docker container
      run: docker run -d -p 8080:80 docker.io/porwalmohit1999/myimage:$(date +%s)

